/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerAdminRouteImport } from './routes/trainer-admin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as TrainersSlugRouteImport } from './routes/trainers.$slug'
import { Route as ClubsSlugRouteImport } from './routes/clubs.$slug'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'

const TrainerAdminRoute = TrainerAdminRouteImport.update({
  id: '/trainer-admin',
  path: '/trainer-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersSlugRoute = TrainersSlugRouteImport.update({
  id: '/trainers/$slug',
  path: '/trainers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/trainer-admin': typeof TrainerAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/trainers/$slug': typeof TrainersSlugRoute
  '/clubs/': typeof ClubsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/trainer-admin': typeof TrainerAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/trainers/$slug': typeof TrainersSlugRoute
  '/clubs': typeof ClubsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/trainer-admin': typeof TrainerAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/trainers/$slug': typeof TrainersSlugRoute
  '/clubs/': typeof ClubsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/search'
    | '/trainer-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/blog/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/clubs/$slug'
    | '/trainers/$slug'
    | '/clubs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/search'
    | '/trainer-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/blog/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/clubs/$slug'
    | '/trainers/$slug'
    | '/clubs'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/search'
    | '/trainer-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/blog/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/clubs/$slug'
    | '/trainers/$slug'
    | '/clubs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TrainerAdminRoute: typeof TrainerAdminRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CitySlugRoute: typeof CitySlugRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  TrainersSlugRoute: typeof TrainersSlugRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer-admin': {
      id: '/trainer-admin'
      path: '/trainer-admin'
      fullPath: '/trainer-admin'
      preLoaderRoute: typeof TrainerAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$slug': {
      id: '/trainers/$slug'
      path: '/trainers/$slug'
      fullPath: '/trainers/$slug'
      preLoaderRoute: typeof TrainersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TrainerAdminRoute: TrainerAdminRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  CitySlugRoute: CitySlugRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  TrainersSlugRoute: TrainersSlugRoute,
  ClubsIndexRoute: ClubsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
