/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerAdminRouteImport } from './routes/trainer-admin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as TrainersSlugRouteImport } from './routes/trainers.$slug'
import { Route as ClubsSlugRouteImport } from './routes/clubs.$slug'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as CategoryParentSlugChildSlugRouteImport } from './routes/category.$parentSlug.$childSlug'
import { Route as CategoriesParentSlugChildSlugRouteImport } from './routes/categories.$parentSlug.$childSlug'

const TrainerAdminRoute = TrainerAdminRouteImport.update({
  id: '/trainer-admin',
  path: '/trainer-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersSlugRoute = TrainersSlugRouteImport.update({
  id: '/trainers/$slug',
  path: '/trainers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryParentSlugChildSlugRoute =
  CategoryParentSlugChildSlugRouteImport.update({
    id: '/category/$parentSlug/$childSlug',
    path: '/category/$parentSlug/$childSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesParentSlugChildSlugRoute =
  CategoriesParentSlugChildSlugRouteImport.update({
    id: '/categories/$parentSlug/$childSlug',
    path: '/categories/$parentSlug/$childSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/trainer-admin': typeof TrainerAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/trainers/$slug': typeof TrainersSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/categories/$parentSlug/$childSlug': typeof CategoriesParentSlugChildSlugRoute
  '/category/$parentSlug/$childSlug': typeof CategoryParentSlugChildSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/trainer-admin': typeof TrainerAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/trainers/$slug': typeof TrainersSlugRoute
  '/categories': typeof CategoriesIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/categories/$parentSlug/$childSlug': typeof CategoriesParentSlugChildSlugRoute
  '/category/$parentSlug/$childSlug': typeof CategoryParentSlugChildSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/trainer-admin': typeof TrainerAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/trainers/$slug': typeof TrainersSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/categories/$parentSlug/$childSlug': typeof CategoriesParentSlugChildSlugRoute
  '/category/$parentSlug/$childSlug': typeof CategoryParentSlugChildSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/search'
    | '/trainer-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/clubs/$slug'
    | '/trainers/$slug'
    | '/categories/'
    | '/clubs/'
    | '/categories/$parentSlug/$childSlug'
    | '/category/$parentSlug/$childSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/search'
    | '/trainer-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/clubs/$slug'
    | '/trainers/$slug'
    | '/categories'
    | '/clubs'
    | '/categories/$parentSlug/$childSlug'
    | '/category/$parentSlug/$childSlug'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/search'
    | '/trainer-admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/clubs/$slug'
    | '/trainers/$slug'
    | '/categories/'
    | '/clubs/'
    | '/categories/$parentSlug/$childSlug'
    | '/category/$parentSlug/$childSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TrainerAdminRoute: typeof TrainerAdminRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CitySlugRoute: typeof CitySlugRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  TrainersSlugRoute: typeof TrainersSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  CategoriesParentSlugChildSlugRoute: typeof CategoriesParentSlugChildSlugRoute
  CategoryParentSlugChildSlugRoute: typeof CategoryParentSlugChildSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer-admin': {
      id: '/trainer-admin'
      path: '/trainer-admin'
      fullPath: '/trainer-admin'
      preLoaderRoute: typeof TrainerAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$slug': {
      id: '/trainers/$slug'
      path: '/trainers/$slug'
      fullPath: '/trainers/$slug'
      preLoaderRoute: typeof TrainersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$parentSlug/$childSlug': {
      id: '/category/$parentSlug/$childSlug'
      path: '/category/$parentSlug/$childSlug'
      fullPath: '/category/$parentSlug/$childSlug'
      preLoaderRoute: typeof CategoryParentSlugChildSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$parentSlug/$childSlug': {
      id: '/categories/$parentSlug/$childSlug'
      path: '/categories/$parentSlug/$childSlug'
      fullPath: '/categories/$parentSlug/$childSlug'
      preLoaderRoute: typeof CategoriesParentSlugChildSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TrainerAdminRoute: TrainerAdminRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  CitySlugRoute: CitySlugRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  TrainersSlugRoute: TrainersSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  CategoriesParentSlugChildSlugRoute: CategoriesParentSlugChildSlugRoute,
  CategoryParentSlugChildSlugRoute: CategoryParentSlugChildSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
